version: '3'

networks:
  web:
    external: true

services:
  db:
    image: postgres:10-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=workaround  # nextcloud wants to create the db itself
      - POSTGRES_USER=nextcloud
    env_file:
      - .env
    volumes:
      - ${DATA_ROOT_DIR:-/srv/data}/cloud/db:/var/lib/postgresql/data

  app:
    image: nextcloud:production-fpm-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
    env_file:
      - .env
    volumes:
      - ${DATA_ROOT_DIR:-/srv/data}/cloud/app:/var/www/html

  web:
    build: .
    restart: unless-stopped
    volumes:
      - ${DATA_ROOT_DIR:-/srv/data}/cloud/app:/var/www/html:ro
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host: cloud.ananas.space, nextcloud.ananas.space, nextcloud.kenh.fr, cloud.kenh.fr"
      traefik.frontend.redirect.permanent: 'true'
      traefik.frontend.redirect.regex: 'https://(.*)/.well-known/(card|cal)dav'
      traefik.frontend.redirect.replacement: 'https://$$1/remote.php/dav/'
    networks:
      - web
      - default

  redis:
    image: redis:alpine

