version: '3'

networks:
  web:
    external: true

services:
  db:
    image: postgres:10-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=nextcloud  # nextcloud wants to create the db itself
      - POSTGRES_USER=nextcloud
    env_file:
      - .env
    volumes:
      - ${DATA_ROOT_DIR:-/srv/data}/cloud/db:/var/lib/postgresql/data

  app:
    image: nextcloud:18-fpm-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
    env_file:
      - .env
    volumes:
      - ${DATA_ROOT_DIR:-/srv/data}/cloud/app:/var/www/html

  web:
    build: .
    restart: unless-stopped
    volumes:
      - ${DATA_ROOT_DIR:-/srv/data}/cloud/app:/var/www/html:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cloud.rule=Host(`cloud.kenh.fr`,`cloud.ananas.space`,`cloud.bjk-fansub.com`,`nextcloud.ananas.space`,`nextcloud.kenh.fr`,`nextcloud.bjk-fansub.com`)"
      - "traefik.http.middlewares.nc-rep.redirectregex.permanent=true"
      - "traefik.http.middlewares.nc-rep.redirectregex.regex=https://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.nc-rep.redirectregex.replacement=https://$$1/remote.php/dav/"
      - "traefik.http.routers.cloud.middlewares=nc-rep"
    networks:
      - web
      - default

  redis:
    restart: unless-stopped
    image: redis:alpine

