version: '3'

networks:
  web:
    external: true

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=nextcloud  # nextcloud wants to create the db itself
      - POSTGRES_USER=nextcloud
    env_file:
      - .env
    volumes:
      - ${DATA_ROOT_DIR:-/srv/data}/cloud/db2:/var/lib/postgresql/data

  app:
    image: nextcloud:25-fpm-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
    env_file:
      - .env
    volumes:
      - ${DATA_ROOT_DIR:-/srv/data}/cloud/app:/var/www/html
    depends_on:
      - db
      - redis

  collabora:
    image: collabora/code
    restart: unless-stopped
    environment:
      - TZ=Europe/Brussels
      - aliasgroup1=https://nextcloud.ananas.space
      - dictionaries=en_US,fr_FR
      - extra_params=--o:ssl.enable=false --o:ssl.termination=true
    env_file:
      - .env
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.collabora.rule=Host(`office.ananas.space`)'
      - 'traefik.http.services.collabora.loadbalancer.server.port=9980'
      - 'traefik.http.middlewares.collabora-header.headers.referrerPolicy=no-referrer'
      - 'traefik.http.middlewares.collabora-header.headers.stsSeconds=15552000'
      - 'traefik.http.middlewares.collabora-header.headers.forceSTSHeader=true'
      - 'traefik.http.middlewares.collabora-header.headers.stsPreload=true'
      - 'traefik.http.middlewares.collabora-header.headers.stsIncludeSubdomains=true'
      - 'traefik.http.middlewares.collabora-header.headers.browserXssFilter=true'
      - 'traefik.http.middlewares.collabora-header.headers.customRequestHeaders.X-Forwarded-Proto=https'
      - 'traefik.http.routers.collabora.middlewares=collabora-header'
    depends_on:
      - app
    networks:
      - web
      - default

  web:
    build: .
    restart: unless-stopped
    volumes:
      - ${DATA_ROOT_DIR:-/srv/data}/cloud/app:/var/www/html:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cloud.rule=Host(`cloud.kenh.fr`,`cloud.ananas.space`,`nextcloud.ananas.space`,`nextcloud.kenh.fr`)"
      - "traefik.http.middlewares.nc-rep.redirectregex.permanent=true"
      - "traefik.http.middlewares.nc-rep.redirectregex.regex=https://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.nc-rep.redirectregex.replacement=https://$$1/remote.php/dav/"
      - "traefik.http.routers.cloud.middlewares=nc-rep"
    depends_on:
      - app
    networks:
      - web
      - default

  redis:
    restart: unless-stopped
    image: redis:alpine

