version: '3'

networks:
  web:
    external: true

services:
  web:
    image: "containous/whoami"
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.kenh.fr`,`whoami.ananas.space`)"

