version: "3"

networks:
  web:
    external: true

services:
  sonarr:
    image: linuxserver/sonarr
    restart: unless-stopped
    networks:
      - web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - UMASK_SET=022 #optional
    volumes:
      - ${CONF_ROOT_DIR:-/srv/docker}/sonarr/config:/config
      - ${DATA_ROOT_DIR:-/srv/data}/downloads:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.ananas.space`)"
      - "traefik.http.routers.sonarr.tls.certresolver=lets"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
      - "traefik.http.routers.sonarr.entrypoints=websecure"
