version: "3"

networks:
  web:
    external: true

services:
  radarr:
    image: linuxserver/sonarr
    restart: unless-stopped
    networks:
      - web
    user: 1000:1000
    environment:
      # - PUID=1000
      # - PGID=1000
      - TZ=Europe/Brussels
      # - UMASK_SET=022 #optional
    volumes:
      - ./config:/config
      - ./data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`sonarr.ig11.ananas.space`)"
      - "traefik.http.routers.radarr.tls.certresolver=lets"
      - "traefik.http.services.radarr.loadbalancer.server.port=8989"
      - "traefik.http.routers.radarr.entrypoints=websecure"
