version: '3'

networks:
  web:
    external: true

services:
  aurbot:
    build: .
    restart: unless-stopped
    environment:
      - AURBOT_DATADIR=/home/build/build
    volumes:
      - ./data/build:/home/build/build
      - ./data/repo:/home/build/repo
      - ./aurbot.conf:/etc/aurbot.conf

  web:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./data/repo:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - web
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host: repo.bjk-fansub.com, repo.ananas.space, repo.kenh.fr"

