version: '3'

services:
  knot:
    image: cznic/knot:latest
    container_name: knot
    restart: unless-stopped
    networks:
      - dns
    ports:
      - "53:53"
      - "53:53/udp"
    volumes:
      - ${CONF_ROOT_DIR:-/srv/docker}/knot/storage:/storage
      - ${CONF_ROOT_DIR:-/srv/docker}/knot/rundir:/rundir
      - ${CONF_ROOT_DIR:-/srv/docker}/knot/config:/config
    command: knotd

networks:
  dns:
    external: true

