version: "3"

networks:
  web:
    external: true

services:
  radarr:
    image: linuxserver/radarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      # - UMASK_SET=022 #optional
    volumes:
      - ./config:/config
      - ./data/movies:/movies
      - ./data/downloads:/downloads
    ports:
      - 7878:7878
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.kenh.fr`,`radarr.ananas.space`)"
      - "traefik.http.routers.radarr.tls.certresolver=lets"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
      - "traefik.http.routers.radarr.entrypoints=websecure"
