version: "3"

networks:
  web:
    external: true

services:
  radarr:
    image: linuxserver/radarr
    restart: unless-stopped
    networks:
      - web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - UMASK_SET=022 #optional
    volumes:
      - ${CONF_ROOT_DIR:-/srv/docker}/radarr/config:/config
      - ${DATA_ROOT_DIR:-/srv/data}/downloads:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.ananas.space`)"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
