## Dynamic configuration

[http.routers]
  [http.routers.traefik]
    rule = "Host(`traefik.dyn.kenh.fr`, `traefik.dyn.ananas.space`)"

#[http.routers]
#  [http.routers.my-router]
#    rule = "Host(`myrouter.localhost`)"
#    service = "my-service"
#    entryPoint = ["websecure","web"]
#  [http.routers.my-router.tls]
#    certResolver = "lets"
#
#[http.services]
#  [http.services.my-service.loadBalancer]
#    [[http.services.my-service.loadBalancer.servers]]
#      url = "http://127.0.0.1"
