version: "3"

networks:
  web:
    external: true

services:
  bitwarden:
    image: vaultwarden/server:alpine
    restart: unless-stopped
    networks:
      - web
    volumes:
      - ${CONF_ROOT_DIR:-/srv/docker}/bitwarden/bw-data:/data
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bitwarden.rule=Host(`pass.ig11.ananas.space`)"
      - "traefik.http.routers.bitwarden.service=bitwarden"
      - "traefik.http.services.bitwarden.loadbalancer.server.port=80"
      - "traefik.http.routers.bitwarden-websocket.rule=Host(`pass.ig11.ananas.space`) && Path(`/notifications/hub`)"
      - "traefik.http.routers.bitwarden-websocket.service=bitwarden-websocket"
      - "traefik.http.services.bitwarden-websocket.loadbalancer.server.port=3012"
