version: "3"

networks:
  web:
    external: true

services:
  deluge:
    image: linuxserver/deluge
    restart: unless-stopped
    # user: 1000:1000
    ports:
      - "8112:8112"
      - "58845-58900:58845-58900"
      - "58845-58900:58845-58900/udp"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - UMASK_SET=022 #optional
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - ${CONF_ROOT_DIR:-/srv/docker}/deluge/config:/config
      - ${DATA_ROOT_DIR:-/srv/data}/downloads:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.deluge.rule=Host(`deluge.bjk-fansub.com`,`deluge.kenh.fr`,`deluge.ananas.space`)"
      - "traefik.http.services.deluge.loadbalancer.server.port=8112"
    networks:
      - web
