version: "3"

services:
  deluge:
    image: linuxserver/deluge
    restart: unless-stopped
    # user: 1000:1000
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - UMASK_SET=022 #optional
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - ${CONF_ROOT_DIR:-/srv/docker}/deluge/config:/config
      - ${DATA_ROOT_DIR:-/srv/data}/downloads:/downloads
      - ./deluge_port_update.sh:/custom-cont-init.d/deluge_port_update.sh
    network_mode: "service:gluetun"
    env_file:
      - .env

  gluetun:
    image: qmcgaw/gluetun
    ports:
      - "8112:8112"
      - "58846:58846"
    cap_add:
      - NET_ADMIN
    networks:
      gluetun_network:
      default:
    env_file:
      - .env

networks:
  gluetun_network:
    external: true

