version: '3'

networks:
  web:
    external: true

services:
  web:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ${CHATONS_ROOT_DIR:-/srv/chatons}/static/${CHATONS_STATIC_SITE:-static}:/usr/share/nginx/html:ro
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host: ${CHATONS_STATIC_SITE:-static}.${CHATONS_DOMAIN:-localhost}, www.${CHATONS_STATIC_SITE:-static}.${CHATONS_DOMAIN:-localhost}"
    networks:
      - web

