version: '3'

networks:
  web:
    external: true

services:
  web:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ${DATA_ROOT_DIR:-/srv/data}/static:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.static.rule=Host(`static.ananas.space`, `static.kenh.fr`)"
    networks:
      - web

