version: '3.1'

networks:
  web:
    external: true

services:
  jellyfin:
    image: jellyfin/jellyfin
    restart: unless-stopped
    user: 1000:1000
    volumes:
      - ${CONF_ROOT_DIR:-/srv/docker}/jellyfin/config:/config
      - ${CONF_ROOT_DIR:-/srv/docker}/jellyfin/cache:/cache
      - ${DATA_ROOT_DIR:-/srv/data}/downloads/jellyfin:/media
    networks:
      - web
    # devices:
      # VAAPI Devices
      # - /dev/dri/renderD128:/dev/dri/renderD128
      # - /dev/dri/card0:/dev/dri/card0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`nitflex.kenh.fr`,`nitflex.ananas.space`)"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
