version: "3"

services:
  valheim:
    image: ghcr.io/lloesche/valheim-server
    restart: unless-stopped
    cap_add:
      - sys_nice
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    env_file:
      - .env
    volumes:
      - ${CONF_ROOT_DIR:-/srv/docker}/valheim/conf:/config
      - ${CONF_ROOT_DIR:-/srv/docker}/valheim/backups:/config/backups
      - ${DATA_ROOT_DIR:-/srv/data}/valheim/server:/opt/valheim

