version: "3"

services:
  valheim:
    image: mbround18/valheim:latest
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    environment:
      TZ: "Europe/Brussels"
      PORT: "2456"
      PUBLIC: "1"
      AUTO_UPDATE: "1"
      AUTO_BACKUP: "1"
      AUTO_BACKUP_SCHEDULE: "30 */1 * * *"
      AUTO_BACKUP_REMOVE_OLD: "1"
      AUTO_BACKUP_DAYS_TO_LIVE: "1"
      AUTO_BACKUP_ON_UPDATE: "1"
      AUTO_BACKUP_ON_SHUTDOWN: "1"
    env_file:
      - .env
    volumes:
      - ${CONF_ROOT_DIR:-/src/docker}/valheim/conf:/home/steam/.config/unity3d/IronGate/Valheim
      - ${CONF_ROOT_DIR:-/src/docker}/valheim/backups:/home/steam/backups
      - ${DATA_ROOT_DIR:-/srv/data}/valheim/server:/home/steam/valheim

