[log]
  level = "INFO" #DEBUG, INFO, WARN, ERROR, FATAL, PANIC
  format = "common"

[global]
  sendAnonymousUsage = false

[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http]
      middlewares = ["security@file"]
      [entryPoints.web.http.redirections.entryPoint]
        to = "websecure"
        scheme = "https"
    [entryPoints.web.forwardedHeaders]
        trustedIPs = ["172.0.0.0/8"]

  [entryPoints.websecure]
    address = ":443"
    [entryPoints.websecure.http]
      middlewares = ["security@file"]
      [entryPoints.websecure.http.tls]
        options = "mytlsoption@file"
        certresolver = "lets"
    [entryPoints.websecure.forwardedHeaders]
        trustedIPs = ["172.0.0.0/8"]

[api]

[providers]
  [providers.docker]
    endpoint = "tcp://socket-proxy:2375"
    network = "web"
    exposedByDefault = false

  [providers.file]
    filename = "/etc/traefik/dynamic_conf.toml"

[certificatesResolvers.lets.acme]
  email = "traefik@ananas.space"
  storage = "acme.json"
  [certificatesResolvers.lets.acme.tlsChallenge]

# [metrics]
#  [metrics.influxDB]
#    address = "influxdb:8086"
#    protocol = "http"
#    database = "traefik"
