[log]
  level = "INFO" #DEBUG, INFO, WARN, ERROR, FATAL, PANIC
  format = "common"

[global]
  sendAnonymousUsage = false

[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http]
      middlewares = ["security@file"]
      [entryPoints.web.http.redirections.entryPoint]
        to = "websecure"
        scheme = "https"

  [entryPoints.websecure]
    address = ":443"
    [entryPoints.websecure.http]
      middlewares = ["security@file"]
      [entryPoints.websecure.http.tls]
        options = "mytlsoption@file"
        certresolver = "lets"

[api]

[providers]
  [providers.docker]
    endpoint = "tcp://socket-proxy:2375"
    network = "web"
    exposedByDefault = false

  [providers.file]
    filename = "/etc/traefik/dynamic_conf.toml"

[certificatesResolvers.lets.acme]
  email = "traefik@ananas.space"
  storage = "acme.json"
  [certificatesResolvers.lets.acme.tlsChallenge]
